config/routes.rb
Rails.application.routes.draw do
  

 
  
  # Recommendspots
  get 'recommendspots/index' => 'recommendspots#index'
  get "recommendspots/new" => "recommendspots#new"
  post "recommendspots/create" => "recommendspots#create"
  
  # Contacts
  get 'contacts/new' => "contacts#new"
  get "contacts/send" => "contacts#send"
  
  
  # Favorites
  # Favorites
  get 'favorites/:id/index' => 'favorites#index'
  post 'favorites/:id/create' => 'favorites#create'
  post "favorites/:id/destroy" => "favorites#destroy"
  
  
  # Chats
  get 'chats/:id/index' => 'chats#index'
  resources :chats, :only => [:show, :create]
  # get 'chats/:id' => 'chats#show'
  # post "chats/create" => "chats#create"
  
  
  # Comments
  get 'comments/:id/index' => 'comments#index'
  post 'comments/create' => 'comments#create'
  get "send" => "comments#send"
  
  
  # Firends
  get "friends/:id/index" => "friends#index"
  get "friends/:id/approval" => "friends#approval"
  get "friends/:id/wait" => "friends#wait"
  get "friends/:id/block" => "friends#block"
  post "friends/:id/create" => "friends#create"
  
  post "friends/:id/accept" => "friends#accept"
  get "friends/:id/request" => "friends#request"
  
  
  # Events
  get "events/index" => "events#index"
  get "events/new" => "events#new"
  get "events/:id" => "events#show"
  post "events/create" => "events#create"
  get  "events/:id/edit" => "events#edit"
  post "events/:id/update" => "events#update"
  post "events/:id/destroy" => "events#destroy"
  post "events/:id/piccreate" => "events#piccreate"
  # Users
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "signup" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"
  post "login" => "users#login"
  post "logout" => "users#logout"
  get "login" => "users#login_form"
  get "users/:id/likes" => "users#likes"
  get "users/:id/setupmenu" => "users#setupmenu"
  get "mail_send" => "users/mail_send"
  
  
  
  # Top
  get '/' => 'blogs#blogsindex'
  get "agreement" => "home#agreement"
  get "qa" => "home#qa"
  get "info" => "home#info"


 # Blogs
  get 'blogs/blogsindex' => 'blogs#blogsindex' 
  # ユーザー全体のブログ一覧
  get "blogs/new" => "blogs#new"
  get "blogs/:id" => "blogs#show"
  post "blogs/create" => "blogs#create"
  get "blogs/:id/edit" => "blogs#edit"
  post "blogs/:id/update" => "blogs#update"
  get "blogs/:id/draftindex" => "blogs#draftindex"
  get "blogs/:id/index" => "blogs#index"
  # ユーザー個人のブログ一覧
  


end

app/models/blog.rb
class Blog < ApplicationRecord
  
  validates :user_id, {presence: true}  
    
  def user
    return User.find_by(id: self.user_id)
  end
  
  belongs_to :user
  has_many :favorites
  has_many :comments
  
  
end

app/models/blogpic.rb
class Blogpic < ApplicationRecord
    
    
    
end

app/models/chat.rb
class Chat < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
    
    belongs_to :blogs
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
    
    def user
      return User.find_by(id: self.user_id)
    end


   has_many :eventpics

end

app/models/eventpic.rb
class Eventpic < ApplicationRecord
    
    belongs_to :event
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    validates :user_id,{presence: true}
    # validetes :blog_id,{presence: true}
    
      belongs_to :user
      belongs_to :blog
end

app/models/friend.rb
class Friend < ApplicationRecord
    
  # belongs_to :follower, class_name: "User"
  # belongs_to :followed, class_name: "User"
  # validates :follower, presence: true
  # validates :followed, presence: true
end

app/models/infopic.rb
class Infopic < ApplicationRecord
end

app/models/recommendspot.rb
class Recommendspot < ApplicationRecord
end

app/models/recommendspotpic.rb
class Recommendspotpic < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
     
   has_secure_password
   
     validates :nickname,{presence: true}
     validates :email,{presence: true,uniqueness: true}
     validates :password,{presence: true}
     
     has_many :friends, dependent: :destroy
     has_many :favorites, dependent: :destroy

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(created_at: :desc)
  end
  
  def show
    @events = Event.find_by(id: params[:id])
    @user = User.find_by(id: @events.user_id)
    @event_pics = Eventpic.where(event_id: @events.id)
    # logger.debug(@event_pics.inspect)
  end
  
  
  def new
    @event = Event.new
  end
  
  def create
    require 'fileutils'
    # logger.debug("--------------------------file_name=#{params[:post][:file_name]}")
    
    @event = Event.new(event_params)
    
    if @event.save
        event_id = Event.last.id

      
          # 画像のアップロード対応
    
          if params[:images]
             save_flag = false
             cnt = 0
             params[:images].each { |image|
             
              @event_pics = Eventpic.new(event_pics_params)
              @event_pics.event_id = event_id
              logger.debug(@event_pics.inspect)
              
              if image.inspect.include?("jpg")
                @event_pics.file_type = "jpg"
              elsif image.inspect.include?("jpeg")
                @event_pics.file_type = "jpeg"
              elsif image.inspect.include?("png")
                @event_pics.file_type = "png"
              elsif image.inspect.include?("mp4")
                @event_pics.file_type = "mp4"
              elsif image.inspect.include?("mov")
                @event_pics.file_type = "mov"
              elsif image.inspect.include?("m4v")
                @event_pics.file_type = "m4v"
              end
              
              logger.debug("--------------------------file_name= #{image.inspect.include?("jpg")}")
              
              dir_path = "public/eventpics/#{event_id}"
              FileUtils.mkdir_p(dir_path) unless FileTest.exist?(dir_path)
              
              @event_pics.file_name = "#{@event.id}-#{cnt+1}.#{@event_pics.file_type}"
              image = params[:images][cnt]
              File.binwrite("public/eventpics/#{event_id}/#{@event_pics.file_name}", image.read)
              cnt += 1
              
              @event_pics.save
              save_flag = true
             }
          
              if save_flag
                flash[:notice] = "イベントを作成しました"
                redirect_to events_index_path
              else 
                render events_new_path
              end
          end
      
      
    else
      render events_new_path
    end
      
  end
  
  
  
  def edit
    @event = Event.find_by(id: params[:id])
  end
  
  
  def update 
   @event = Event.find_by(id: params[:id])
   @event.update(
                 title: params[:title],
                 content: params[:content],
                 target: params[:target],
                 event_date: params[:event_date],
                 event_start: params[:event_start],
                 place: params[:place]
                 )
     if @event.save
        redirect_to("/events/index")
     else
        render("event/edit")
     end 
  
  
  def piccreate
    @event = Event.find_by(id: params[:id])
    @eventpic = Eventpic.new(
                             event_id: @event.id,
                             pic: params[:pic]
                             )
  end
 
  end
  
  def destroy
    @event = Event.find_by(id: params[:id])
   if  @event.destroy
     redirect_to("/events/index")
   end
  end

  private 
    def event_params
      params.require(:event).permit(:title, :target, :event_date, :event_start, :place, :price, :user_id, :content).merge(:user_id => @current_user.id)
    end
    
    def event_pics_params
      params.require(:event).permit(:pic)
    end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="main events-new">
  <div class="container">
    <h1 class="form-heading">イベントを編集</h1>
    <%= form_tag("/events/#{@event.id}/update") do %>
    <div class="form">
      <div class="form-body">
          <div class="form-title">
               <p>イベント名</p>
               <textarea name="title"><%= @event.title %></textarea> 
          </div>
          <div class="form-content">
               <p>内容</p>
               <textarea name="content"><%= @event.content %></textarea>
          </div>
          <div class="form-target">
               <p>対象</p>
               <textarea name="target"><%= @event.target %></textarea> 
          </div>
          <div class="form-date">
              <p>日程</p>
               <textarea name="event_date"><%= @event.event_date %></textarea> 
          </div>
          <div class="form-start">
              <p>開始時間</p>
               <textarea name="event_start"><%= @event.event_start %></textarea> 
          </div>
          <div class="form-place">
              <p>料金</p>
               <textarea name="place"><%= @event.place %></textarea> 
          </div>
        <input type="submit" value="公開">
      </div>
     </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="main events-index">
  <div class="container">
     <h1 class="events-heading">イベント情報</h1>
      <% if @current_user %>
        <ul class="events-menus">
           <p>
             <%= link_to("イベントを作成する", "/events/new") %>
           </p>
     <% end %>
       <% @events.each do |event| %>
         <div class="events-index-item">
          <%= link_to(event.title, "/events/#{event.id}") %>
         </div>
       <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="main events-new">
  <div class="container">
    <h1 class="form-heading">イベントを作成</h1>
    <%= form_for @event, url: events_create_path, :html => { multipart: true } do |e| %>
    <div class="form">
      <div class="form-body">
          <div class="form-title">
               <%= e.label :"イベント名*" %>
               <%= e.text_field :title, :class => "event-title-form", required: true %>
          </div>
          <div class="form-content">
               <%= e.label :"内容*" %>
               <%= e.text_area :content, :class => "event-content-form", required: true %>
          </div>
          <div class="form-target">
               <%= e.label :"対象者*" %>
               <%= e.text_field :target, :class => "event-target-form", required: true %>
          </div>
          <div class="form-date">
               <%= e.label :"日程*" %>
               <%= e.date_field :event_date, :class => "event-date-form", required: true %>
          </div>
          <div class="form-place">
               <%= e.label :"開催場所*" %>
               <%= e.text_field :place, :class => "event-place-form", required: true %>
          </div>
          <div class="form-start">
               <%= e.label :"開始時間*" %>
               <%= e.time_field :event_start, :class => "event-start-form", required: true %>
          </div>
          <div class="form-price">
               <%= e.label :"料金*" %>
               <%= e.number_field :price, min:0 ,:class => "event-price-form", required: true %>円
          </div>
          <div class="form-pic">
               <%= e.label :"画像" %>
               <ul>
                 <li>ファイル複数選択：<%= file_field_tag "images[]", type: :file, multiple: true, :class => "event-pic-form" %></li>
               </ul>
          </div>
          <div class="actions">
              <%= e.submit "作成する", :class => "event-form-btn" %>
          </div>
      </div>
     </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="main events-show">
  <div class="container">
    <div class="events-show-item">
       <div class="eventologist">
          <p>主催者</p>
          <%= @user.nickname %>
       </div>
       <div class="events-titlet">
          <p>タイトル</p>
          <%= @events.title %>
       </div>
       <div class="events-content">
          <p>イベント内容</p>
          <%= @events.content %>
       </div>
       <div class="event-date">
          <p>日にち</p>
        <%= @events.event_date %>
       </div>
       <div class="event-start">
          <p>イベント開始時間</p>
        <%= @events.event_start %>
       </div>
       <div class="event-place">
          <p>開催場所</p>
        <%= @events.place %>
       </div>       
       <div class="event-price">
          <p>料金</p>
        <%= @events.price %>
       </div>
       <div class="event-target">
          <p>対象者</p>
        <%= @events.target %>
       </div>
         <% unless @event_pics.pic.empty? %>
            <div class="event_pics">
              <ul>
                <% @event_pics.pic.each do |p| %>
                  <li id="pic_<%= p.id %>">
                    <%= image_tag p.image.url %>
                  </li>
                <% end %>
              </ul>
            </div>
         <% end %>
       <% if @user.id == @current_user.id %>
       <div class="event-menus">
         <%= link_to("編集","/events/#{@events.id}/edit") %>
         <%= link_to("削除","/events/#{@events.id}/destroy", {method: "post"}) %>
        <% end %>
       </div>
    </div>
  </div>
</div>